site_name: "UniversaLabeler Documentation"
site_url: ""
repo_url: "https://github.com/NehorayMelamed/UniversialLabel"
theme:
  name: "material"
  palette:
    - scheme: "slate"
      primary: "blue grey"
      accent: "light blue"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
    - scheme: "default"
      primary: "blue grey"
      accent: "blue"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"
  font:
    text: "Roboto"
    code: "Fira Code"
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.footer  # Add this
    - search.highlight
    - search.suggest
    - toc.integrate
    - toc.follow
    - toc.sticky
    - content.code.copy
    - content.code.annotate


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_style: monokai
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.escapeall
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      title: "On this page"

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Installation:
          - Overview: user-guide/installation/overview.md
          - Platforms: user-guide/installation/platforms.md
          - Environment Setup: user-guide/installation/environment-setup.md
          - Package Installation: user-guide/installation/package-installation.md
          - Models Download: user-guide/installation/models-download.md
      - Usage:
          - Get started usage: user-guide/usage/get-started-usage.md
          - Basic Usage: user-guide/usage/basic-usage.md
  - Development:
      - Architecture: development/architecture.md
      - Model Integration: development/model-integration.md
      - Pipelines creation: development/advanced-usage-pipelines.md
  - About: about.md
  - Contact Us: contact.md
  - License: license.md

